### ISSUE TITLE
Audio_Server

### ISSUE THREAD

**Issue by freesig** [freesig/cpal#27]
Currently the spatial audio server targets Nannou 0.5, I forked 0.8 not realizing this but I could just fork and older commit or we could try and get the audio server onto 0.8.
I've fixed a few minor things already but stuck on:
```rust
error[E0277]: the trait bound `gui::custom_widget::sound::Sound<'a>: nannou::ui::widget::Common` is not satisfied
  --> src/lib\gui\custom_widget\sound.rs:78:10
   |
78 | impl<'a> Widget for Sound<'a> {
   |          ^^^^^^ the trait `nannou::ui::widget::Common` is not implemented for `gui::custom_widget::sound::Sound<'a>`
```
Do you think its there would be much todo to get audio server onto 0.8 @mitchmindtree ?

**Comment by mitchmindtree** [comment]
Ahh I think audio server might have been written before conrod got "derive" for things like `WidgetCommon` and `WidgetStyle`, by the looks of that error anyways. Maybe I'll have a go at updating it to the latest nannou now? Will let you know how it goes.

**Comment by freesig** [comment]
## Running this on windows
- The updated branch runs on mac fine.
- When it's set to ASIO backend it runs and opens. I get the gui and the speakers but I can't spawn any sounds.
- When its set to Wasapi backend it builds without error but when run it just hangs. No GUI launches and no errors are printing. 
- Wasapi and Asio both work fine in the cpal examples.
- It freezes on exit but this is true for nannou aswell. It's due to the fact that there's no call to remove streams and no way to do it on drop due to the "infinite loop" in EventLoop. We should probably call it manually from nannou
## Todo
- [x] Try running nannou with Wasapi. _Yep nannou freezes on simple audio example with Wasapi backend_
- [x] nannou can't find supported sample formats for Wasapi. So I'll fix this that way I can see if the audio server will run on wasapi and then I know there is something wrong with ASIO __Was just that nannou doesn't support 48000__
- [ ] There is a lot of Mutex used at the lower levels of the ASIO backend so it's possible that a dead lock is happening. Could set all locks to try_lock inside loops and see if they are blocking lots.
- [x] `println!("{}", file!(), line!());` in the thread responsible for spawning audio and see where it stops.

**Comment by freesig** [comment]
Ok finally got it to load with Wasapi and it has the exact same symptoms as Asio.
So it's nothing in the ASIO code. I'll try and see where it's getting stuck

Can confirm that the output render thread is not running
